### ISSUE TITLE
Spanish stock market missing

### ISSUE THREAD

**Issue by juasiepo** [yccheok/jstock#1]
JStock says that
Spain no longer supported as Yahoo! decides to discontinue Spain data feed.

But I can see Spanish Data on yahoo

http://finance.yahoo.com/q/cp?s=^IBEX

**Comment by dnlngl** [comment]
Hi Everyone,

How can change the sotck feed for spain? We will try to change the call to Yahoo finance to google finance for Spain stocks.

I hope you can help us!

thanks in advance

dani

**Comment by juasiepo** [comment]
Spanish prices can be found in JSON/XML format from this link
https://github.com/davidayalas/yql-stocks
