### ISSUE TITLE
options aren't loaded (on Ubuntu 18.04.3)

### ISSUE THREAD

**Issue by fallenguru** [yccheok/jstock#139]
jstock 1.0.7.39 on Ubuntu 18.04.3, openjdk-11-jre and matching openjfx (also tried v8, no difference).

Options, from the most recently active tab on the main window to anything in Options-Options will not *load* on startup (but default values used instead). These default values will then be saved on program exit, overwriting the initially correctly *saved* values. The actual data (watchlists, buys, sells, ...) is fine.

Steps to reproduce:
1) Copy the .jstock from a working & configured (Windows) installation to ~/.jstock.
2) Run jstock.
3) Observe that everything has reset to default.

Alternative steps to reproduce:
1) Remove ~/.jstock.
2) Run jstock. (~/.jstock is created & populated.)
3) Enable Options-Options-Broker fee, add a new broker, name "testbroker".
4) Quit jstock. (Observe that ~/.jstock/1.0.7/config/options.xml now contains <org.yccheok.jstock.portfolio.BrokingFirm> <name>testbroker</name>.)
5) Run jstock again, open Options window, see that Broker fee is unchecked again, and no brokers listed.
6) Quit jstock. (Observe that ~/.jstock/1.0.7/config/options.xml no longer has "testbroker".)

**Comment by fallenguru** [comment]
Tried with the proprietary Oracle jre (jre1.8.0_221), that works. I'd rather use the jre provided by the OS vendor, though, so I'd like to get to the bottom of this.

How can I enable logging? I tried editing config/commons-logging.properties, even removing it entirely, but I don't get anything on stderr (regardless of the java version used).

**Comment by yccheok** [comment]
@fallenguru 

Thanks for reporting this. Currently, I'm not able to reproducing this problem due to lack of access to Linux machine. I will try to find out a way to get it up and running.

**Comment by fallenguru** [comment]
FWIW, I find that [VirtualBox](https://www.virtualbox.org/) is a quick way to get a Linux environment, or even multiple different ones, running on a Windows host.

**Comment by yccheok** [comment]
Yes. Thank you. I think I found the root cause of not able to restore
config. But, I still need time to resolve cloud feature in openjdk. As,
cloud feature is using javafx. Openjdk seems to have poor support in javafx.

fallenguru <notifications@github.com> 於 2019年11月21日 週四 上午12:40 寫道：

**Comment by yccheok** [comment]
@fallenguru 

I have fixed the problem, with instruction on how to install Java right here : https://jstock.org/help_install_upgrade.html#upgrade-linux

Now, JStock should be able to run under openjdk 11. Can you kindly try it out with latest JStock release, and let us know the outcome? Thank you.

**Comment by fallenguru** [comment]
Didn't test extensively, but it seems to work fine now using OpenJDK 11 with OpenJFX. Thank you!
