### ISSUE TITLE
Question: Data source in the code

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [yccheok/jstock#172]
Dear Mr. Cheok,

I tried to contact via mail but did not receive an answer.

I am not sure if JStock is what I need. I played a bit arround with it but had problems adding single elements/stocks to the watchlist. The watchlist fills up with everything available. I am not able to select single stocks and add them to watchlist. Maybe I missunderstand the intention of JStock and the watchlist?

I also looked into the code. But Java is not my home so it is a bit hard for me. **I tried to find out where JStock got its data from. Can you give me a hint about this?**

Then I would be able to writ my own Python script for my own very simple needs.

I want to "watch" single stocks and ETFs.
I want an alarm (e.g. via EMail) if the today price is (e.g.) 5%
lower/higher compared to the price one week in the past.
My intention is to be informed about curve bends.

Two examples of my portfolio.

```
"Bershire Hathaway B"
WKN: A0YJQ2 / ISIN: US0846707026 / Symbol: BRK.B

"Vanguard FTSE Developed Asia Pacific ex Japan UCITS ETF (USD)
Accumulating" ISIN: IE00BK5BQZ41 | WKN: A2PLTA | Kürzel: VGEK
```

Can I do this with JStock or the data source you use?

Kind regards
Christian Buhtz
https://codeberg.org/buhtz/

**Comment by DNS** [comment]
Probably from:
https://query1.finance.yahoo.com/v7/finance/quote?fields=regularMarketPrice&symbols=BRK-B

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
> Probably from: https://query1.finance.yahoo.com/v7/finance/quote?fields=regularMarketPrice&symbols=BRK-B
Is this documentated somewhere?
How would I get historical data; e.g. price on each day on the last 5 years?

**Comment by DNS** [comment]
There's no documentation. 
You should check yahoo finance to download the historical data in *.csv files.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I can recommend https://github.com/ranaroussi/yfinance which use Python and `pandas` to access yfinance.
