### ISSUE TITLE
Use CNBC as source

### ISSUE THREAD

**Issue by BernardoLima** [yccheok/jstock#29]
Hello, thank you for creating jStock.
I'm wondering if you think it would be a good idea to use CNBC as source since they're really real time, when yahoo finance and google finance are delayed.

I could help you to create CNBC API, would be really simple to create it using regex, since they don't have a webservice I guess.

**Comment by yccheok** [comment]
I prefer not do perform regex on web page text, as they are extremely unreliable. You need to frequent update your code to catch up with their changes. I would say, the effort being invested doesn't worth it. - Poor ROI :)
