### ISSUE TITLE
How to get MACD chart and historgram in jstock ubuntu

### ISSUE THREAD

**Issue by potholiday** [yccheok/jstock#33]
I am using jstock in my ubuntu system . I uses MACD chart and histogram to study the trading  of a stock. MACD is considered as an important tool for trading stocks but I am unable to find MACD option under `technical analysis`. It has RSI, EMA, MFI but no MACD tool. Is there a way to add MACD chart and histogram to the technical analysis chart?

**Comment by RandallSell** [comment]
I'm sure Cheok will have more to add on this, but I will briefly throw in my 2 cents here... MACD is in the charting system, but temporarily removed. So if you are keen to grab the source and compile it (with one line of code uncommented) you will have your MACD.

Why it has been temporarily removed I don't know. I did give it a whirl and it seemed to work fine. I'm sure Cheok will be able to shed more light on the topic as well as a timeline hopefully (I'd like to see it in the system as well).

hth
-randall

**Comment by potholiday** [comment]
@RandallSell thanks for the quick reply. so they have temporary removed MACD. currently i am using Java run time enviroment (JRE) to run jstock and didnt installed java itself. So if i have to compile the source code do i need java?.  Can you tell the steps to activate MACD from source code

**Comment by RandallSell** [comment]
You will need NetBeans in order to compile it. And the JStock source is here:
https://github.com/yccheok/jstock/archive/master.zip

I believe NetBeans has the JDK within it, but if it doesn't I believe it will guide you through installing it.

Once you have NetBeans going and you can load the JStock project, do a search for "TEMP DISABLE MACD" And un-comment those lines. Recompile and Bob's your uncle!

BUT be warned - I'm sure there is a good reason why it is currently disabled. It appears to work, but one would need to manually do the math to cross-check and confirm it is actually working. I kinda have that "let's-push-the-button-and-see-what-happens" mentality, which can be a death trap if you are not careful. So be fore-warned that the results may not be accurate.

good luck,
-randall

**Comment by potholiday** [comment]
which line should i uncomment.. I got a result similar to this

````
            //TEMP DISABLE MACD
            // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            if (ta != TA.MACD) {
                this.jMenu2.add(menu);
            }
        }   // for
        this.jMenu2.add(new javax.swing.JSeparator());
        javax.swing.JMenuItem item = new javax.swing.JMenuItem();
        item.setText(GUIBundle.getString("ChartJDialog_ClearAll")); // NOI18N
        item.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChartJDialog.this.clearAll();
            }
        });
        this.jMenu2.add(item);
    }
```

and also **jstock.sh** is exiting without showing anything . any idea what is wrong in

```
#!/bin/bash
#
# Normally, editing this script should not be required.
# Only case is to set up JAVA_HOME if it's not already defined.
#
# To specify an alternative JVM, edit and uncomment the following 
# line and change the path accordingly.
#JAVA_HOME=/usr/lib/java

_JAVA_EXEC="java"
if [ -n $JAVA_HOME ] ; then
    _TMP="$JAVA_HOME/bin/java"
    if [ -f "$_TMP" ] ; then
        if [ -x "$_TMP" ] ; then
            _JAVA_EXEC="$_TMP"
        else
            echo "Warning: $_TMP is not executable"
        fi
    else
        echo "Warning: $_TMP does not exist"
    fi
fi
if ! which "$_JAVA_EXEC" >/dev/null ; then
    echo "Error: No Java Runtime Environment found"
    echo "Please set the environment variable JAVA_HOME to the root directory of your SUN Java installation, e.g. by editing the 7th line in this launcher script."
    exit 1
fi

#
# Resolve the location of the JStock installation.
# This includes resolving any symlinks.
PRG=$0
while [ -h "$PRG" ]; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '^.*-> \(.*\)$' 2>/dev/null`
    if expr "$link" : '^/' 2> /dev/null >/dev/null; then
        PRG="$link"
    else
        PRG="`dirname "$PRG"`/$link"
    fi
done

JSTOCK_BIN=`dirname "$PRG"`
cd "${JSTOCK_BIN}"

_VMOPTIONS="-Xms64m -Xmx512m"
$_JAVA_EXEC $_VMOPTIONS -jar jstock.jar
```

**Comment by RandallSell** [comment]
Comment out the IF test so all menu items are added a la:
            //if (ta != TA.MACD) {
                this.jMenu2.add(menu);
            //}

As for Unix compiling, you are on your own there. I'm a Windows Geek. But based on the error, seems you do not have a JDK installed, or at least NetBeans doesn't know where to find it. I'd google "download JDK" get the latest for your OS and install that, then search around NetBeans for where you tell it which JDK you are running. Just my hunch.

regards,
-randall

**Comment by potholiday** [comment]
I successfully executed jstock from netbeans but uncommenting MACD is still a problem. this is my un commented  code.. still MACD option not showing in jstock

````
  //TEMP DISABLE MACD
            // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
           
            if (ta != TA.MACD) {
                this.jMenu2.add(menu);
            }
        }   
        this.jMenu2.add(new javax.swing.JSeparator());
        javax.swing.JMenuItem item = new javax.swing.JMenuItem();
        item.setText(GUIBundle.getString("ChartJDialog_ClearAll")); // NOI18N
        item.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChartJDialog.this.clearAll();
            }
        });
        this.jMenu2.add(item);
    }

````

Any way thanks for your help. it seems the problem is somewhere else in the source code

**Comment by RandallSell** [comment]
Sorry you need to comment out 2 lines, not un-comment them.

As I explained previously, you want this:
            //if (ta != TA.MACD) {    THIS LINE COMMENTED OUT
                this.jMenu2.add(menu);
            //}  THIS LINE COMMENTED OUT

That way all menu items are created and you will see the MACD stuff.

regards,
-randall

**Comment by potholiday** [comment]
@RandallSell I am extremely sorry for causing any trouble and thank you for taking your time for explaining the solution. English is not my mother tongue so I have misunderstood your explanation. I thought **comment out** means to remove comment and not to add comment. Any way your solution WORKED I have now MACD option in my jstock. once more thank you for your patience and kind explanation

**Comment by potholiday** [comment]
K this is my last query..what files or folders needed to be transferred from newly compiled jstock (with MACD) to the older jstock (without MACD). Both jstocks are in different folder.

filles/folders in the old jstock (without MACD) 

```
config    docs   jstock-1.0.7.8-bin.zip   lib
database  extra  jstock.jar              jstock.sh
```
