### ISSUE TITLE
Adding custom conditions to watchlist

### ISSUE THREAD

**Issue by potholiday** [yccheok/jstock#35]
is it there a way to add custom conditions to watch list

eg:

```
if (change% is between +2 and +5 percentage)
{
show the stocks of those companies in watch list
}
```

**Comment by RandallSell** [comment]
You might be able to use the Stock Indicator Scanner. Download the pre-made ones eg MACD, MFI, RSI and CCI to get a feel for how you can build your own. I haven't done so myself but from the looks of things, that should do what you are looking for.

cheers,
-randall

**Comment by potholiday** [comment]
I have already installed Stock Indicator Scanner and it scans for up and down signal for MACD, MFI, RSI etc. I don't want to do that I just want to see stocks in watchllist whose change percentage is between certain variable (this case +2-5) thats it. If i knew java i myself would have added a small button to watchlist for adding conditions to watchilst for all the columns in it. Sadly java is hard and its not my cup of tea.

**Comment by RandallSell** [comment]
Change percentage over what time period? The day? If so, that is fairly easy - use the Stock Indicator Editor. I built one is about 10 minutes (I didn't know how to to it either but stumbled through it, fairly straight forward when you have the examples to work from). And it doesn't require any knowledge of Java to do it.

The only down side to the Scanner is that it only will work on the "current" watchlist. If you have multiple watch lists it is not so useful. It is on my todo list to allow it to scan across all my watchlists. So the only work around for that ATM is to have an "everything" watch list which combines all your items.

hth
-randall

**Comment by potholiday** [comment]
Yes i have to find change percentage for one day. So how can we do it using Stock Indicator Editor. I opened a Stock Indicator Editor but i don't know how to proceed further. Do you have a tutorial for making stock indicator using that editor

**Comment by RandallSell** [comment]
Well, just combine the two... Create another item for under 5% like what you did for the 2% rule. Use the two with an AND operator (eg must be over 2% AND under 5%) and pipe that to the alert. Follow me? So the GreaterOrEqual (2%) is ANDED with the LesserOrEqual (5%) and pipe that to "alert".

hth
-randall

**Comment by potholiday** [comment]
Thanks it worked I followed your method and its showing the watchlist between 2 and 5 change percentage. Once more thank you for the advice
