### ISSUE TITLE
How to open google finance page of a stock from jstock watchlist

### ISSUE THREAD

**Issue by potholiday** [yccheok/jstock#36]
I know that jstock fetches stock details from google finanace (realtime) and yahoo finance (delayed). As in my jstock watchlist I am using google finance (realtime) to fetch details. Is there a way to open those stocks page in google finance from jstock in a browser or in jstock.

Example
This is the page of [pepsico](http://www.google.com/finance?cid=27011) in google finance and i have **PEP** in my watchlist. If i open the menu (using third mouse) of **PEP** stock, currently we have these three options **History**, **buy** and **delete**. it will be better to add another option **Visit** or something like that; to open the stocks page in  google/yahoo finance

**P.S. Watch list includes scanner also**

**Comment by yccheok** [comment]
Currently, such feature is not available *yet*

**Comment by potholiday** [comment]
@yccheok  are you willing to consider this option in future versions?
