### ISSUE TITLE
What is the difference between stock relative. stock history information and real time stock information

### ISSUE THREAD

**Issue by potholiday** [yccheok/jstock#37]
Can you explain the  difference between stock relative, stock history information and real time stock information. I am trying to create my own indicator and came across this problem. From the words i am able to conclude that real time stock information gives real time data (current time) of a stock but what does **stock relative** and  **stock history** information means. When we have to use those values

**Comment by yccheok** [comment]
Please refer to http://jstock.org/help_stock_indicator_editor.html

**Comment by potholiday** [comment]
k thanks got it
