### ISSUE TITLE
How to add different countries benchmark index chart to jstock watchlist

### ISSUE THREAD

**Issue by potholiday** [yccheok/jstock#43]
I want to add different countries benchmark indexs like Shanghai, Hang Seng, Nikkei 225,BSE Sensex, EURO STOXX 50 etc. to jstock watchlist for chart analysis. can it be done?

**Comment by RandallSell** [comment]
Hi Potholiday,

Did you get a response on this? It can be done but sorting out the ticker is the hard bit. For example the S&P 500 is ^GSPC. The Euro Stoxx 50 is ^STOXX50E. Just google "ticker symbol xxxxxxxx" to get it. I believe all the index start with ^

hth
-randall

**Comment by potholiday** [comment]
@RandallSell 
Hi randall,
Once more thank you for the quick reply. The ticker symbol is from yahoo finance and able to successfully download Nikkie 225 ^N225.


Thanks :+1:  :)
