### ISSUE TITLE
How to encrypt & password protect jstock and supporting data's (Ubuntu)

### ISSUE THREAD

**Issue by potholiday** [yccheok/jstock#44]
Is there any inbuilt feature in jstock to encrypt and password protect jstock GUI and its data. I want to personalize jstock and wants to prevent others using my computer to access jstock.

**Comment by RandallSell** [comment]
Hi Potholiday,

I don't think JStock has any security built into it (a la just for JStock). You will need to protect that at the operating system level. Provided you are not sharing your login, your data (for your login) is isolated from any other users logging in, provided they don't have admin permission. In other words, Unix/Linux/Ubuntu is the only way to secure JStock data from mischievous eyes. And by default (like Windows Visa +) each user's data is isolated.

regards,
-randall

**Comment by potholiday** [comment]
If jstock has this function it would be nice because we are using it for trading with money and it gives an additional layer of security for our portfolio
