### ISSUE TITLE
Issue with visual chart analysis

### ISSUE THREAD

**Issue by potholiday** [yccheok/jstock#47]
Its difficult to do technical chart analysis using jstock.

eg i have a RSI 7 day chart and its difficult to get a meaningful, over brought and over sold signal using jstock chart

This chart from jstock
![Jstock](http://i.imgur.com/VWWZbQX.png)

This chart from tradingview
![chart from tradingview](http://i.imgur.com/5AmRJNW.png)

Both have the similar duration and ticks for the same stock.  I can get a useful signal from tradingview app than jstock. It also happens with MACD indicator (enabled from source code)

**Recommendation**
* change the y axis interval (currently its 25 change it to 5 or 10)

**Comment by RandallSell** [comment]
G'day PotHoliday,

Has no one responded to you on this? I agree that your TradingView image is nicer, particularly with the coloured bands. You can achieve similar using the Zoom-In feature of the chart. right-click | Zoom-In | Range Values. Sadly these reset if you adjust the duration.

Certainly another nice thing that could be added to the list of things to improve in the product.

Recall that you can also use the Stock Indicator Scanner. The pre-built RSI is RSI 14d. So you would probably want to clone that to create your RSI 7.

i know, it is not exactly what you asked for, but another way to get the details you want in a less-then-perfect way.

regards,
-randall

**Comment by potholiday** [comment]
Hi @RandallSell l,
I regularly uses Stock Indicator Scanner for fetching stocks of particular parameters but after scanning i do a visual analysis before picking a stock. Because jstock chart analysis is basics i have to use other services like tradingview for advance analysis. I really love jstock and wishes it to improve its software and charting tools. I think that jstock has a potential to become a powerful trading tool but which needs some more improvements and these small suggestion may help to reach that point

:+1:  :+1: 
regards
PotHoliday
