### ISSUE TITLE
How to submit indicators for jstock

### ISSUE THREAD

**Issue by potholiday** [yccheok/jstock#48]
Hi all,
I have made some simple indicators using jstock and want to submit here. The current indicators uses Golden cross rule for finding up trends and Death cross to find down trend in a market. 

Hope you all like it

[Death cross](http://s000.tinyupload.com/index.php?file_id=06649391428678281793)
[Golden cross](http://s000.tinyupload.com/index.php?file_id=91066392266452887275)

potholiday

**Comment by RandallSell** [comment]
@yccheok - do you intend to add these to the install process of the Indicator Install Wizard?
@potholiday - congrats on contributing.

-randall

**Comment by yccheok** [comment]
Thanks for the contribution. Is it possible that you can provide some simple info on what the indicator does?

Something looks like this : https://github.com/yccheok/jstock/blob/master/appengine/jstock-static/war/alert_indicators/RSISellSignal.html

You can post text here. After that, I shall publish them

**Comment by potholiday** [comment]
@RandallSell  thank you, i will try to add more indicators in the future
@yccheok 

is this enough
Golden Cross
```
Indicator: Golden Cross

Usage: Up Trend signal

Author: Potholiday

Homepage: http://jstock.sourceforge.net

EMA50 > EMA200

A crossover involving a security's short-term moving average breaking above its long-term moving average or resistance level and it indicates a bull market
```

Death Cross
```
Indicator: Death Cross

Usage: Down Trend signal

Author: Potholiday

Homepage: http://jstock.sourceforge.net

EMA50 < EMA200

A crossover resulting from a security's long-term moving average breaking above its short-term moving average or support level and it indicates a bear market
```

**Comment by potholiday** [comment]
Another indicators to find Top losers and Gainers in the market

Top Gainers
http://s000.tinyupload.com/index.php?file_id=63889256216309487212
```
Indicator: Top Gainers 

Usage: Find top gainers in the market

Author: Potholiday

Homepage: https://github.com/potholiday

Change_price_percentage > 5%

Looks for stocks whose change in price percentage is more than five percentage

```
Top Losers
http://s000.tinyupload.com/index.php?file_id=67764749126264558420
```
Indicator: Top Losers

Usage: Find top losers in the market

Author: Potholiday

Homepage: https://github.com/potholiday

Change_price_percentage < -5%

Looks for stocks whose change in price percentage is less than negative five percentage
```

**Comment by yccheok** [comment]
@potholiday Hi, I just upload all your files. Can you use JStock app to try your indicators, to see whether they work as expected? Thank you very much

**Comment by RandallSell** [comment]
I can confirm that they are available on the JStock Server, they download fine and seem to be working. I didn't actualyl cross-check any formulas. Just downloaded and used them to scan.

-randall

**Comment by potholiday** [comment]
@yccheok @RandallSell sorry for the late reply was been away from my system. Any way thanks for including my indicators
