### ISSUE TITLE
standard deviation in function for indicator

### ISSUE THREAD

**Issue by bboycs** [yccheok/jstock#50]
HI, anyone there? just to check with you guys regarding on the function for the relative stock history. As i search from previous request in sourceforge, the standard deviation has been accept on 27/10/2009, so i just wanna check with you guys how is the progress on it.
thanks

**Comment by yccheok** [comment]
It had been stopped quite some time, as our current focus is mainly on mobile app. Perhaps, you can let us know how "standard deviation" function is useful to you, then we might consider to kick start the development.

**Comment by potholiday** [comment]
@yccheok  even i was looking for Standard deviation for calculating Bolinger band. It would be very helpful if you can reintroduce standard deviation also If possible can you introduce conditional statement(like if..else) to jstock scanner.

**Comment by bboycs** [comment]
@yccheok 
hi, firstly i would like to thanks jstock team for create such wonderful and useful tools for us, and thanks for you reply too. Indeed standard deviation is a key for build for bolinger band which is very useful for doing technical analysis scanning.
Anyway i appreciate the contribution of jstock team
cheer.

**Comment by yccheok** [comment]
Thanks for input. I will then include such block.

**Comment by bboycs** [comment]
@yccheok  thank you very much

**Comment by yccheok** [comment]
Hi, can you guys preview whether this code changes is something which you wish to have?

https://github.com/yccheok/jstock/commit/0da2feb2a76e896a30aaed7668c954bed05cfd0b

**Comment by yccheok** [comment]
This has been released - https://github.com/yccheok/jstock/releases/tag/release_1-0-7-10

**Comment by bboycs** [comment]
@yccheok  hi, sorry for late reply and thanks for help to add on the standard deviation..
