### ISSUE TITLE
Cloud import between Jstock Android and Jstock Linux

### ISSUE THREAD

**Issue by xmodulo** [yccheok/jstock#55]
Hi,

I was testing cloud save/load feature using Jstock Android (0.9.83) and Linux (1.0.7.10) versions.
First I saved my portfolio to cloud from Jstock Android (I checked jstock-xxxxx.zip successfully created on Google Drive). Then I launched Jstock Linux version, and chose "Open from Cloud".  It said "Loading from cloud successful" on Linux version, but the portfolio remained empty.

Does cloud backup work across Jstock Android and Linux versions?   Such cross platform backup would be really useful...

**Comment by yccheok** [comment]
@xmodulo It should work seamless. Please check that, you are in correct Watchlist/Portfolio.

**Comment by xmodulo** [comment]
What do you mean by "Please check that, you are in correct Watchlist/Portfolio."

Cloud load doesn't work for me.   jstock-****zip uploaded by Android Jstock contains jstock configuration and all my buy/sell history and watchlist info.  But for some reason Linux Jstock doesn't seem to be able to load it from Google Drive.  How do I troubleshoot this issue?

**Comment by yccheok** [comment]
I'm mean, after you "Open from Cloud" in JStock desktop, you should see some new selection items under "Portfolio" menu, isn't it?

**Comment by xmodulo** [comment]
No.

This is what I did:
1. Install Jstock Linux fresh.
2. Create a "test" watch list and "test" Portfolio.
3. Load data from cloud (which contains one watch list ("X"), and two portfolios ("A" and "B").
4. I don't see any new watch list or portfolio added on Jstock Linux.

After 3, I expect watch list "X" and portfolios "A" and "B are automatically imported to Jstock Linux.  But  nothing is added after 3.

**Comment by yccheok** [comment]
1) How is data "(which contains one watch list ("X"), and two portfolios ("A" and "B")" being saved to cloud initially? Are you using latest JStock Android?

2) When load from cloud, are you using same Google account as you save to cloud?

**Comment by yccheok** [comment]
Also, please check your Google Drive content. It should contain "jstock-fe78....zip"

**Comment by xmodulo** [comment]
I am saving to the cloud using the latest Jstock Android.  jstock zip file uploaded by Android version has the following content:

  inflating: android/watchlistinfos.csv  
  inflating: android/portfolioinfos.csv  
  inflating: android/indices.csv     
  inflating: android/jstockoptions.json  
  inflating: UnitedState/portfolios/A/buyportfolio.csv  
  inflating: UnitedState/portfolios/A/portfolio-real-time-info.json  
  inflating: UnitedState/portfolios/A/sellportfolio.csv  
  inflating: UnitedState/portfolios/A/dividendsummary.csv  
  inflating: UnitedState/portfolios/B/buyportfolio.csv  
  inflating: UnitedState/portfolios/B/portfolio-real-time-info.json  
  inflating: UnitedState/portfolios/B/sellportfolio.csv  
  inflating: UnitedState/portfolios/B/dividendsummary.csv  
  inflating: UnitedState/watchlist/X/realtimestock.csv 

As far as I can see, the file content looks normal.

On Linux version I am loading from the same Google account which has the above zip file.

**Comment by yccheok** [comment]
In desktop, do you switch the country to United States?

**Comment by xmodulo** [comment]
Yes, that was it!
I see the country is set to Malaysia by default. When I switched to US, I see all the stocks now.

Thanks for your prompt reply.  I'm planning to cover Jstock on my Linux site.  You will soon be featured.
Keep up the good work :P

**Comment by yccheok** [comment]
Looks like I should have a better way to help user to select country after
loading from cloud...

On Tue, Dec 8, 2015 at 1:07 PM, Dan Nanni <notifications@github.com> wrote:

> Yes, that was it!
> I see the country is set to Malaysia by default. When I switched to US, I
> see all the stocks now.
>
> Thanks for your prompt reply. I'm planning to cover Jstock on my Linux
> site. You will soon be featured.
> Keep up the good work :P
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yccheok/jstock/issues/55#issuecomment-162766477>.
>



-- 
Thanks and Regards
Yan Cheng Cheok

**Comment by yccheok** [comment]
@xmodulo Thanks for willing to feature JStock in your Linux site.

**Comment by xmodulo** [comment]
Just publish it:
http://xmodulo.com/stock-portfolio-management-software-linux.html

Keep up the good work!  :)

**Comment by yccheok** [comment]
Thanks for the write up! Appreciated that.

Just one note, current JStock requires Java 8, not Java 7 :)

On Mon, Jan 4, 2016 at 1:40 PM, Dan Nanni <notifications@github.com> wrote:

> Just publish it:
> http://xmodulo.com/stock-portfolio-management-software-linux.html
>
> Keep up the good work! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yccheok/jstock/issues/55#issuecomment-168587101>.
>



-- 
Thanks and Regards
Yan Cheng Cheok
