### ISSUE TITLE
Real time price candle absent from historical charts

### ISSUE THREAD

**Issue by potholiday** [yccheok/jstock#61]
Basically I have two questions

**first**

I want to know why I cant find today’s real time price candle(+) in historical charts (EOD data)
_(+)= Not minute by minute but single  candle with todays high, low, last price and open_
eg
today Feb 9 (trading time) if i check historical data for past month of any stock I only get stock till previous day that is feb 8 and not todays candle

Is it possible you can add real time candles to EOD historical data.It will be easier to visualize the chart.

**Second question**

while scanning with indicators do jstock consider todays real time data or only till previous day EOD da

**Comment by yccheok** [comment]
Do you mean you want the information of Feb 9 during market closed?

**Comment by Unaventures** [comment]
Wow you are up late responding to user requests ! Must be around 2 AM in
KL. :)
