### ISSUE TITLE
Having problem with the connection with the server

### ISSUE THREAD

**Issue by muhdsuffian90** [yccheok/jstock#67]
![1](https://cloud.githubusercontent.com/assets/19768472/15810704/1e661818-2b56-11e6-9c21-105ea82bf73b.PNG)
Before this it work as it should. but now when I try to use the screener, it does not retrieve any data from the server. When i switch to different network, i can retrive the data for a while, but still after a period of time it facing the same problem

![2](https://cloud.githubusercontent.com/assets/19768472/15810705/1e6fb53a-2b56-11e6-9c2f-9122201ab7ff.PNG)
The same problem when i try to manually retrieve the data. it only show failed to retrieve the data. 

Is it the problem with the server or i should change the setting on my side?
Btw. keep on going. i see a huge potential in Jstock.

**Comment by yccheok** [comment]
May I know, are you still facing the same problem on all stocks, or only selected stock?

**Comment by muhdsuffian90** [comment]
No sir, everything have work just fine. the problem Im facing prior was due to my ignorance to stop the screener once it reach 100%. yahoo will block my ip from obtaining the stock quotes because they though i keep spamming their server. to avoid this, i just stop whenever the screener reach the 100%. the problem is solve. may i suggest that you guys could put a check button for me to automatically stop the screener when it reach 100% that would be great. Thank you.
