### ISSUE TITLE
Could you add Argentina as Country?

### ISSUE THREAD

**Issue by LRancez** [yccheok/jstock#68]
Hi there,
First of, thanks for keep it up this cool project!
Could you add Argentina as country? The Argentinian market index is MERVAL
Thanks!

**Comment by yccheok** [comment]
No worry man. We are working in progress.

Let's say, for Agrometal SAI, I'm going to design its stock code as

ARGO.AR

the suffix .AR is being used so that JStock can recognize it as Argentina stock. Does that make sense to you?

**Comment by Guisardo** [comment]
Hi @yccheok, thanks for the response!
I think that is mostly a personal choice at this point :smile:  but if you ask me, most of the time I use .BA as suffix or BCBA: as prefix:
ARGO.BA
BCBA:ARGO

It comes from 'Buenos Aires Stock Exchange' (BA) and 'Bolsa de Comercio de Buenos Aires' (BCBA)

In Argentina we also have another market that are starting to raise. It is called Rofex (Rosario Futures Exchange). But I'm not sure how easy is to get the values of those, so lets start with BA for now.

**Comment by LRancez** [comment]
Hi @yccheok, thanks for the response!
I think that is mostly a personal choice at this point :smile:  but if you ask me, most of the time I use .BA as suffix or BCBA: as prefix:
ARGO.BA
BCBA:ARGO

It comes from 'Buenos Aires Stock Exchange' (BA) and 'Bolsa de Comercio de Buenos Aires' (BCBA)

In Argentina we also have another market that are starting to raise. It is called Rofex (Rosario Futures Exchange). But I'm not sure how easy is to get the values of those, so lets start with BA for now.

**Comment by yccheok** [comment]
Hi @LRancez 

The reason I use .AR, as it is much easier to use country code as stock code suffix. If I use major stock exchange as their stock code prefix

- I don't know what is the best 2 letter code for BCBA. Should I use BC, or BA. I will face the same problem for other country stock exchange as well.
- High chance of 2 letter code conflict, with other country stock exchange.

Here are the stock code suffix, we plan to use for each country

Argentina - .AR
Finland - .FI
Russia - .RU
Saudi Arabia - .S (I don't use .SA, as it is conflicting with Brazil's Yahoo code suffix)
South Africa - .ZA
Thailand - .TH
Turkey - .TR

The complete list of stock code suffix (Please refer to 'Yahoo code suffix' column) can be found from https://docs.google.com/spreadsheets/d/1mZ8yjF25Ugsrr13_UkUfSGT0fXKa5ggH6_-kR2F-LXc/edit#gid=0

The complete stock code list for each country can be found here

Argentina - https://github.com/yccheok/jstock/blob/master/appengine/jstock-static/war/stocks_information/argentina/stocks.csv

Finland - https://github.com/yccheok/jstock/blob/master/appengine/jstock-static/war/stocks_information/finland/stocks.csv

Russia - https://github.com/yccheok/jstock/blob/master/appengine/jstock-static/war/stocks_information/russia/stocks.csv

Saudi Arabia - https://github.com/yccheok/jstock/blob/master/appengine/jstock-static/war/stocks_information/saudiarabia/stocks.csv

South Africa - https://github.com/yccheok/jstock/blob/master/appengine/jstock-static/war/stocks_information/southafrica/stocks.csv

Thailand - https://github.com/yccheok/jstock/blob/master/appengine/jstock-static/war/stocks_information/thailand/stocks.csv

Turkey - https://github.com/yccheok/jstock/blob/master/appengine/jstock-static/war/stocks_information/turkey/stocks.csv

If you have any opinion on the new stock code suffix, or you have found any mistake in the complete stock code list, please kindly let me know.

Thank you.

**Comment by LRancez** [comment]
Hi @yccheok,
Thanks for your time on this!

Be aware that the stocks suffix represents a market, not a country, and the most known Argentinian market is the Buenos Aires Stock Exchange, Besides yahoo uses .BA too for the Argentinian stocks so using BA as suffix like them should not cause any conflicts:
http://finance.yahoo.com/exchanges?bypass=true

Best,

**Comment by LRancez** [comment]
FYI: in this spreadsheet says that yahoo uses AR but it is incorrect, it uses BA:
https://docs.google.com/spreadsheets/d/1mZ8yjF25Ugsrr13_UkUfSGT0fXKa5ggH6_-kR2F-LXc/edit#gid=0

http://finance.yahoo.com/exchanges?bypass=true

**Comment by yccheok** [comment]
Thanks for pointing out my mistake.

**Comment by LRancez** [comment]
Hi there,
I see that the last release (release_1-0-7-16) is including a lot of new countries! (one of them being Argentina)
Thanks for the help and for keeping up this cool project!
Best,
