### ISSUE TITLE
how to get industry?

### ISSUE THREAD

**Issue by think-nice-things** [yccheok/jstock#75]
Hi,

I'd like to trigger signals on a specific industry.
Currently the only "industry" shown is "Unknown".

I guess that the industry information is from the country specific database file like

~/.jstock/1.0.7/UnitedState/database/stock-info-database.csv

Any hints how to get the industry information in there for each stock?

**Comment by yccheok** [comment]
Sorry for late reply. Super busy recently :(

The Industry field is there, for legacy purpose. As, I don't find any stock server, which can provide useful information on that particular field. Hence, that's why I mark it as "Unknown".
