### ISSUE TITLE
More data - Intraday Minutes Data!

### ISSUE THREAD

**Issue by b6arat6** [yccheok/jstock#77]
Hi @yccheok,

Thanks for creating such an useful project,

As an intraday trader, I look for more data for trading - Intraday minutes data.

Could you add a way to use the intraday minutes data along with time in building indicators?

Use case:
1. In intraday, if a stock consolidates for a period in a flat manner, you could expect a sudden upward movement at any point.

**Comment by yccheok** [comment]
Sorry. We don't have access to intra day data.
