### ISSUE TITLE
File menubar is broken if you dismiss Google auth dialog

### ISSUE THREAD

**Issue by javabrett** [yccheok/jstock#92]
1. File -> Open from Cloud.
2. Dismiss that dialog.
3. Notice that the File menu is now not selectable.

**Comment by shuwnyuantee** [comment]
Hi @javabrett , I am a developer from JStock team. May I know which OS you are running on?

**Comment by javabrett** [comment]
Linux Ubuntu running gnome. I don't have the exact version I was running at the time.

**Comment by shuwnyuantee** [comment]
Hi Bret,

I see. How about now, if you try running latest JStock with your current
environment? Thanks.

**Comment by javabrett** [comment]
Same behaviour in 1.0.7.21.  To see the problem, you need to dismiss the Cloud login dialog using the window close handle.  Note that the File menu is disabled when this dialog is raised - looks like there must be a missing listener to re-enable it.

This was found due to #86 when the Cloud login doesn't load at all due to no proxy being configured.

**Comment by javabrett** [comment]
Hmmm just started working for me on 1.0.7.21.  Not sure what happened with the first test.  Looks like this is fixed, thanks.
